<?php

use Utils\SohelRana820\Utility\Utility;

class UtilityTests extends PHPUnit_Framework_TestCase
{
    /**
     * @var Utility;
     */
    protected $utility;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->utility = new Utility();
    }

    public function testArrayKeyValueSearch()
    {
        $array = array(
            0 => array(
                'user' => array(
                    'name' => 'AAA',
                    'role' => 'admin',
                )
            ),
            1 => array(
                'user' => array(
                    'name' => 'BBB',
                    'role' => 'dealer',
                )
            ),
            3 => array(
                'user' => array(
                    'name' => 'CCC',
                    'role' => 'dealer',
                )
            ),
            4 => array(
                'user' => array(
                    'name' => 'DDD',
                    'role' => 'agent',
                )
            ),
            5 => array(
                'user' => array(
                    'name' => 'EEE',
                    'role' => 'agent',
                )
            ),
        );

        $result = $this->utility->arrayKeyValueSearch($array, 'role', 'agent');
        var_dump($result);

    }
}