<?php

use Utils\SohelRana820\Networks\Networks;

class NetworksTests extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testParseHostNameFunctionReturningHostName()
    {
        $hostname = Networks::parseHostName('http://sohelrana.me/php');
        $this->assertTrue($hostname == 'sohelrana.me');
    }

    public function testParseHostIPReturningValidIp()
    {
        $ip = Networks::parseHostIP('http://sohelrana.me/php');
        $this->assertTrue(filter_var($ip, FILTER_VALIDATE_IP) == true);
    }

    public function testParseDnsInfoReturningDnsInfo()
    {
        $dnsInfo = Networks::parseDnsInfo('http://sohelrana.me/php');
        $this->assertTrue(is_array($dnsInfo));
    }
}